name: Build and deploy Laravel app to Azure Web App - VShop

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          php --version
          composer install --prefer-dist --no-progress

      - name: Zip Artifact for Deployment
        run: zip -r release.zip ./

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__CLIENTIDSECRETNAME__ }}
          tenant-id: ${{ secrets.__TENANTIDSECRETNAME__ }}
          subscription-id: ${{ secrets.__SUBSCRIPTIONIDSECRETNAME__ }}

      - name: Verify Azure Login
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show

      - name: List Azure Subscriptions
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account list --output table

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VShop'
          package: release.zip
