# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Laravel app to Azure Web App - VShop

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          php --version
          composer install --prefer-dist --no-progress

      - name: Zip Artifact for Deployment
        run: zip -r release.zip ./

      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTIDSECRETNAME }}
          tenant-id: ${{ secrets.TENANTIDSECRETNAME }}
          subscription-id: ${{ secrets.SUBSCRIPTIONIDSECRETNAME }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show